USE [master]
GO

/****** Object:  Database [AnswerDB]    Script Date: 03/27/2018 20:08:09 ******/
CREATE DATABASE [AnswerDB] ON  PRIMARY 
( NAME = N'AnswerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AnswerDB.mdf' , SIZE = 7168KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AnswerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AnswerDB_log.ldf' , SIZE = 39296KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AnswerDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AnswerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AnswerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AnswerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AnswerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AnswerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AnswerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AnswerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AnswerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AnswerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AnswerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AnswerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AnswerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AnswerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AnswerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AnswerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AnswerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AnswerDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AnswerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AnswerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AnswerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AnswerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AnswerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AnswerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AnswerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AnswerDB] SET  READ_WRITE 
GO

ALTER DATABASE [AnswerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [AnswerDB] SET  MULTI_USER 
GO

ALTER DATABASE [AnswerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AnswerDB] SET DB_CHAINING OFF 
GO


USE [AnswerDB]
GO

/****** Object:  Table [dbo].[T_UserInfo]    Script Date: 03/27/2018 20:08:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_UserInfo](
	[Uid] [nchar](20) NOT NULL,
	[Pwd] [nchar](20) NOT NULL,
	[Name] [nchar](10) NOT NULL,
	[Class] [int] NOT NULL,
	[Token] [nchar](100) NULL,
	[TokenCreateTime] [datetime] NULL,
	[RegTime] [datetime] NOT NULL,
	[LastLoginTime] [datetime] NULL,
	[Locking] [bit] NOT NULL,
	[isAdmin] [bit] NOT NULL,
	[isComplete] [bit] NOT NULL,
 CONSTRAINT [PK_T_UserInfo] PRIMARY KEY CLUSTERED 
(
	[Uid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [AnswerDB]
GO

/****** Object:  Table [dbo].[T_QuestionsInfo]    Script Date: 03/27/2018 20:08:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_QuestionsInfo](
	[Q_ID] [int] NOT NULL,
	[Q_Content] [nchar](200) NOT NULL,
	[Q_Option1] [nchar](50) NOT NULL,
	[Q_Option2] [nchar](50) NOT NULL,
	[Q_Option3] [nchar](50) NOT NULL,
	[Q_Option4] [nchar](50) NOT NULL,
	[Q_PassOption] [int] NOT NULL,
	[Q_Score] [int] NOT NULL,
 CONSTRAINT [PK_T_Questions] PRIMARY KEY CLUSTERED 
(
	[Q_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [AnswerDB]
GO

/****** Object:  Table [dbo].[T_Class]    Script Date: 03/27/2018 20:08:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_Class](
	[ClassID] [int] IDENTITY(1,1) NOT NULL,
	[ClassName] [nchar](20) NOT NULL,
 CONSTRAINT [PK_T_Class] PRIMARY KEY CLUSTERED 
(
	[ClassID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [AnswerDB]
GO

/****** Object:  Table [dbo].[T_AnswerRecord]    Script Date: 03/27/2018 20:08:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_AnswerRecord](
	[R_ID] [int] IDENTITY(1,1) NOT NULL,
	[R_Uid] [nchar](20) NOT NULL,
	[R_Grage] [int] NOT NULL,
	[R_StartTime] [datetime] NOT NULL,
	[R_SubmitTime] [datetime] NULL,
 CONSTRAINT [PK_T_AnswerRecord] PRIMARY KEY CLUSTERED 
(
	[R_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO




